### ISSUE TITLE
Pidtrymka "İ" (LATIN CAPITAL LETTER I WITH DOT ABOVE)

### ISSUE THREAD

**Issue by pfactum** [paiv/latynka#19]
Dobroho zdorovja.

Jakym pravylom možna zastavyty kapitalizyvaty "i" jak "İ" (jak u turećkij movi, iz krapočkoju)?

Ďakuju.

**Comment by paiv** [comment]
Hi. This tool does not differentiate transliterating Cyrillic lower case or upper case, the rule is the same for both.
