### ISSUE TITLE
Пропозиція

### ISSUE THREAD

**Issue by dj3underscores** [paiv/latynka#2]
Було б чудово, аби можна було прив’язати конкретну систему транслітерації до конкретного домену.

А то дещо незручно щораз перемикатися на иншу систему на иншому сайті…

Крім того, не завадило б реалізувати додавання своїх таблиць транслітерації в налаштуваннях розширення (а то мені довелося розбирати, переробляти й збирати розширення вручну під себе)…

**Comment by paiv** [comment]
> Крім того, не завадило б реалізувати додавання своїх таблиць транслітерації в налаштуваннях розширення

V nalaštuvanńax obyrajte zi spysku najavnyx tablyć, ta tysnit́ "redaguvaty" – ce j bude dodavanńam svojeï.

> Було б чудово, аби можна було прив’язати конкретну систему транслітерації до конкретного домену.

Ćogo ne bude, ale pan maje navyčky:

> мені довелося розбирати, переробляти й збирати розширення вручну під себе

👍
