### ISSUE TITLE
Проблема з спеціальними літерами у верхньому регістрі і наступними літерами після них (ПІСНЯ -> PISŃa)

### ISSUE THREAD

**Issue by ivaschia** [paiv/latynka#21]
Існує проблема, коли при наявності правила на кшталт  `я:
  cons: \u0301a
  other: ja` і текстом написаному повністю верхнім регістром наступна літера не стає такою, а залишається маленькою, або тою що прописана у правилі. Тобто вихідом б було додавання правила для великої Я, але це заборонено. Прохання розглянути ось цей недолік
![image](https://user-images.githubusercontent.com/37184485/235311312-9d3a4f85-9e83-4e38-8141-286a139aacb2.png)

**Comment by paiv** [comment]
Hi. This is a long-standing issue, but needs too much effort to fix properly. Here are some initial test cases, for future reference:

| uk | uk-latn |
| -- | -- |
| є | je |
|Є|JE|
|єва|jeva|
|Єва|Jeva|
|ЄВА|JEVA|
|ієна|ijena|
|Ієна|Ijena|
|ІЄНА|IJENA|
|п'є|p'je|
|П'є|P'je|
|П'Є|P'JE|
|має|maje|
|Має|Maje|
|МАЄ|MAJE|
|тієї|tijeji|
|Тієї|Tijeji|
|ТІЄЇ|TIJEJI|
|Дрозд Є.О.|Drozd J.O. <br> or Drozd Je.O.|

| uk | uk-latn |
| -- | -- |
|я|ja|
| приг + я | cons + ◌́a |
|Я|JA|
|ня|ńa|
|Ня|Ńa|
|НЯ|ŃA|
|нЯ|ńA|
|м'я|mja|
|М'я|Mja|
|М'Я|MJA|
|м'Я|mjA|

| uk | uk-latn |
| -- | -- |
|г|h|
|зг|zgh|
|Зг|Zgh|
|ЗГ|ZGH|
|зГ|zH|
|згин|zghyn|
|Згин|Zghyn|
|ЗГИН|ZGHYN|
|узгірок|uzghirok|
|Узгірок|Uzghirok|
|УЗГІРОК|UZGHIROK|
|пелазг|pelazgh|
|Пелазг|Pelazgh|
|ПЕЛАЗГ|PELAZGH|
|ДЗГ|DZH|
|ЗГТ|ZHT|
|РЗГА|RZHA|

**Comment by paiv** [comment]
Case correctness is not the priority for this project.
As a workaround, the page should rely on CSS `text-transform: uppercase;`
