### ISSUE TITLE
Додати таблицю абетки від Максима Прудеуса

### ISSUE THREAD

**Issue by Krypton-86** [paiv/latynka#22]
Блогер запропонував альтернативну латинку простішу та більш доступну для сприйняття людьми.
відео: [Українська латинка: усі "за" та "проти" | Кирилиця чи латиниця | Абетка та розкладка клавіатури](https://youtu.be/nHeE2x2UNw4?si=DwAsxNnD9cWHpADB&t=1680)

**Comment by paiv** [comment]
@Krypton-86 Добрий день. Альтернативних латинок "від блогерів" існує з два десятки. Нова латинка мусить мати суттєві підстави. "простішу та більш доступну" – порівняно з чим? Новий стандарт ДСТУ 9112:2021 набув чинність 2022-04-01, але Прудеус не порівнює свою систему зі стандартом, і не перелічує переваг. Хоча його система не збігається зі стандартом лишень десь на 15%. Тому я не бачу підстав додавати таку латинку до інших. А гнучкість цього проєкта в тім, що вам є можливість додати в свій бравзер будь-яку нову латинку, і поширювати її серед друзів.

**Comment by paiv** [comment]
Додавати до вбудованих латинок підстав не має, а в свій бравзер додати нову латинку можна в Параметрах (налаштування розширення).
