### ISSUE TITLE
пропозиція латинки Прудеуса

### ISSUE THREAD

**Issue by seesmof** [paiv/latynka#23]
вітаю ✝️💓🙏🏼 не хочете додати [латинку Прудеуса](https://drukarnia.com.ua/articles/ukrayinska-latinka-maibutnye-nashoyi-krayini-ITKqx)? вона дуже схожа на латинку НаЧасі, але там м'який знак та апостроф однаково апострофом позначаються, і замість ї використовують ji

якшо відкрию PR, то просто додати файлик `prudeus.json` до `src/data/bundled_tables/`? осьо як думаю зробити:
```json
{
    "id": "prudeus",
    "title": "Prudeus",
    "description": "[стаття](https://drukarnia.com.ua/articles/ukrayinska-latinka-maibutnye-nashoyi-krayini-ITKqx), [відео](https://youtu.be/nHeE2x2UNw4)",
    "rules": {
        "а": "a",
        "б": "b",
        "в": "v",
        "г": "g",
        "ґ": "ĝ",
        "д": "d",
        "дь": "d'",
        "е": "e",
        "є": "je",
        "ж": "ž",
        "з": "z",
        "зь": "z'",
        "и": "y",
        "і": "i",
        "ї": "ji",
        "й": "j",
        "к": "k",
        "л": "l",
        "ль": "l'",
        "м": "m",
        "н": "n",
        "нь": "n'",
        "о": "o",
        "п": "p",
        "р": "r",
        "рь": "r'",
        "с": "s",
        "сь": "s'",
        "т": "t",
        "ть": "t'",
        "у": "u",
        "ф": "f",
        "х": "h",
        "ц": "c",
        "ць": "c'",
        "ч": "č",
        "ш": "š",
        "щ": "šč",
        "ь": "'",
        "ю": "ju",
        "я": "ja",
        "'": "'"
    }
}
```
[приклад](https://paiv.github.io/latynka/v1?r=1%271%2711a11b11v11g1111d22d%2711e12je1111z22z%2711y11i12ji11j11k11l22l%2711m11n22n%2711o11p11r22r%2711s22s%2711t22t%2711u11f11h11c2111111211%2712ju12ja%2Dk0ow0dea65ukvpca450be34keea4f5f9fd4mqg5fd8mrg9fmgd3npgd6nsgtgd0od2od4o0g1g2gd8ozg0grpva2anrjjvq38aog64akmkg874b)

хай ГОСПОДЬ Ісус Христос наш Святий Живий БОГ Всемогутній Всевишній благословляє вас ✝️💞

**Comment by paiv** [comment]
@seesmof Добрий день. З виходом національного стандарту транслітерації ДСТУ 9112:2021 пропозиції альтернативних систем латинки мають доводити свої переваги над стандартом, і мусять мати суттєві відмінності від вже наявних в списку.

#22 Додавати до вбудованих латинок підстав не має, а в свій бравзер додати нову латинку можна в Параметрах (налаштування розширення).
