### ISSUE TITLE
Non-syllabic sounds

### ISSUE THREAD

**Issue by najemnik3838** [paiv/latynka#26]
Non-syllabic sounds are very common in Slavic languages and Ukrainian, they appear after vowels and before consonants. Many Slavic languages and some Ukrainian orthographies have the unstressed ǔ. Is it possible to make it so that, for example «v» be always “ǔ”, besides when it is after cons and between the vowels. Thanks!

Молоко в лісі —> Moloko ǔ lisi, Пішов —> pišoǔ.

**Comment by paiv** [comment]
@najemnik3838 This project is focused on transliteration of Cyrillic source, which for Ukrainian language does not provide this distinction.

> «v» be always “ǔ”, besides when it is after cons and between the vowels

You can try defining all letter combinations with <в>, longer rules take precedence over shorter rules, and final rule will be the singe <в>:
- жв: zhv
- уві: uvi
- ...
- в: ǔ

**Comment by najemnik3838** [comment]
Thanks for your answer! I‘ve tried doing this, but this gives me ‘’undefined’’ text.

**Comment by paiv** [comment]
> this gives me ‘’undefined’’ text

Sure, there are some known issues in the engine. Please open another ticket with details.

**Comment by najemnik3838** [comment]
This “undefined” thing appears only when I’m trying to "Bypass the system" by transliterating non existing letter in ukrainian cyrillic. I don’t think this is a major issue and it needs so much attention, but it would be nice to add an option of changing a letter when it is between the vowels. Like this: 
в: ǔ
 cons: v
 between the vowels: v (this option does not exists right now)
 start: v
 
 Thanks!
